### ISSUE TITLE
Task MW Goto Location doesn't work because forgeting set up MoveTarget.Forward.

### ISSUE THREAD

**Issue by qq1021582988** [Ji-Rath/MassAIExample#9]
Hi, Thank you for your share.
I found entities will stand when X > 0. After debugging, I found you forget set up MoveTarget.Forward In MW_GotoLocation.cpp.It causes UMassSteerToMoveTargetProcessor failes.

MoveTarget.Forward = (Destination - TransformFragment.GetTransform().GetLocation()).GetSafeNormal();

**Comment by Ji-Rath** [comment]
Nice catch! I've pushed a fix to address this issue 1cfc8d9
